# Makefile

tp1:
	docker exec -i M2_SQL_COURSE mysql -u root TP -t < ./scripts/TP1.sql | tee logs/tp1.log

tp2:
	docker exec -i M2_SQL_COURSE mysql -u root TP -t < ./scripts/TP2.sql | tee logs/tp2.log

tp3:
	docker exec -i M2_SQL_COURSE mysql -u root TP -t < ./scripts/TP3.sql | tee logs/tp3.log

project:
	docker exec -i M2_SQL_COURSE mysql -u root TP -t < ./scripts/DANJOU_Arthur.sql | tee logs/project.log