# Makefile

tp1:
	docker exec -i M2_SQL_COURSE mysql -u root TP -t < ./scripts/TP1.sql | tee logs/tp1.log

tp2:
	docker exec -i M2_SQL_COURSE mysql -u root TP -t < ./scripts/TP2.sql | tee logs/tp2.log